### ISSUE TITLE
Respect nomagic

### ISSUE THREAD

**Issue by Bellaktris** [pgdouyon/vim-evanesco#13]
When I search for ** I got E871 (cannot have multi follow multi) in toggle_hlsearch. 
I have set nomagic in my vimrc. Do you think you can handle nomagic case too?

**Comment by pgdouyon** [comment]
Should be fixed now, can you try pulling the latest and let me know if you still see the bug?

**Comment by Bellaktris** [comment]
Yeah, it works now. Thank you.
