### ISSUE TITLE
VISUAL * search is not silent

### ISSUE THREAD

**Issue by oblitum** [pgdouyon/vim-evanesco#16]
\* search causes `:call evanesco#evanesco_star_end()` to appear in command line and be part of command history.

**Comment by pgdouyon** [comment]
I pushed up a fix that I think should do the trick. Can you pull the latest and let me know if you still see the command output?

**Comment by oblitum** [comment]
I just tried but the fix doesn't look quite right. Now when I type `/` for a search I see command blink in the command line.

**Comment by oblitum** [comment]
I can only see this in Alacritty, which as GPU based terminal emulator. On termite I can't see it happening.

**Comment by oblitum** [comment]
Ah sorry.

This behavior is not due to this fix. So no problem regarding the fix, it's working.

I just started using Alacritty yesterday, and evanesco causes that with it, I think b/c its rendering is faster.

**Comment by pgdouyon** [comment]
I modified the mappings for `/` and `?` in a way that will hopefully prevent the command from blinking on screen. Can you pull the latest again and let me know if you still see it?

**Comment by oblitum** [comment]
@pgdouyon yeah thanks, that's also fixed now.
