### ISSUE TITLE
Visual star search not working for all selections

### ISSUE THREAD

**Issue by felixSchl** [pgdouyon/vim-evanesco#4]
I've been using other visual star search plugins before but they did not work on all selections. Your visual star search works a lot better, however I also found some patterns that won't work. When I select the text `[a]` and hit `*`, it will look for `a`s, not for `[a]` - I guess that's vim doing a regex search.

**Comment by pgdouyon** [comment]
Great catch thanks for pointing that out.  Should be fixed with the latest commit.

**Comment by felixSchl** [comment]
Cool will give it a whirl
