### ISSUE TITLE
Problems with searching for ===

### ISSUE THREAD

**Issue by novadev94** [pgdouyon/vim-evanesco#7]
I'm having some problems while searching for `===` (the problem is also shown for other length: `=`, `==`,...).

This is the error shown

```
Error detected while processing function <SNR>103_toggle_hlsearch[7]..<SNR>103_search_executed:
line    3:
E864: \%#= can only be followed by 0, 1, or 2. The automatic engine will be used
```

Steps to reproduce
1. Type `/===`.  
2. Hit `<Enter>`.  
3. Error shown. Hit `<Enter>` again to ignore it.

**Comment by pgdouyon** [comment]
Yea I had vaguely noticed this a few times before but hadn't bothered to track it down.  Thanks for coming up with a reproducible case, should be fixed now.

**Comment by novadev94** [comment]
Thanks for making this great plugin, @pgdouyon!
