### ISSUE TITLE
Folds are closed while searching

### ISSUE THREAD

**Issue by sudo-nice** [pgdouyon/vim-evanesco#8]
In spite of native search method, folds are staying closed while we are searching with vim-evanesco. So, now we have to open folds before the search to reveal the matched patterns.
Great plugin, btw. :wink:

**Comment by pgdouyon** [comment]
Good catch, Evanesco should respect the value of the `'foldopen'` option now.  Let me know if this doesn't fix the problem for you.

**Comment by sudo-nice** [comment]
Thank you!
